name: Uboot Ubuntu CI Build
run-name: Uboot - ${{ inputs.board }} (${{ inputs.soc }})

on:
  workflow_dispatch:
    inputs:
      soc:
        required: true
        description: SOC/CPU Model
        type: choice
        default: mt7981
        options:
          - 'mt7981'
          - 'mt7986'
      board:
        required: true
        description: Router Model Name
        type: choice
        default: ax3000t
        options:
          - 'ax3000t'
          - '360t7'
          - 'cmcc_rax3000m_emmc'
          - 'cmcc_rax3000m'
      multi-layout:
        required: true
        description: Enable Multiple Flash Layout Support
        type: choice
        default: '1'
        options:
          - '0'
          - '1'
      runs-on:
        required: true
        description: Runs on...
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest

jobs:
  ubuntu-build:
    name: Build on ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Get build dept.
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu build-essential flex bison libssl-dev
      - name: Build it
        id: compile
        run: |
          ./build.sh
          echo "release_tag=bl-mt798x-Uboot-$(date +%Y.%m.%d)" >> $GITHUB_ENV
          echo "release_name=bl-mt798x-Uboot" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT
        env:
          SOC: ${{ inputs.soc }}
          BOARD: ${{ inputs.board }}
          MULTI_LAYOUT: ${{ inputs.multi-layout }}
          
      - name: Upload Uboot directory
        uses: actions/upload-artifact@v4
        with:
          #name: Uboot - ${{ inputs.board }} (${{ inputs.soc }})
          name: ${{ env.release_tag }}
          path: output/*.bin
          
      - name: Check space usage
        if: (!cancelled())
        run: df -hT

      - name: Organize files
        id: organize
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
           #  tar -cvf openwrt/bin/targets/mediatek/mt7981/packages.tar openwrt/bin/packages
           cd output
           rm -rf packages
           rm -rf feeds.buildinfo
           rm -rf sha256sums
           rm -rf version.buildinfo
           rm -rf *kernel.bin
           rm -rf *manifest
           rm -rf *tar.bz2
           echo "FIRMWARE=$PWD" >> $GITHUB_ENV
           echo "status=success" >> $GITHUB_OUTPUT
        
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v2
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
           name: ${{ env.release_name }}
           tag_name: ${{ env.release_tag }}
           body: |
             Gateway：192.168.50.1
             Password：password
             Application：mwan3，ramfree，ua2f
           files: ${{ env.FIRMWARE }}/*

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
